services:
  db:
    image: postgres
    container_name: gpt-heist-db
    restart: no
    ports:
      - 5432:5432
    volumes:
      - gpt-heist-db-data:/var/lib/postgresql/data
    env_file: .env
  pgadmin:
    image: dpage/pgadmin4
    container_name: gpt-heist-db-viewer
    restart: no
    ports:
      - "3003:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.a
      PGADMIN_DEFAULT_PASSWORD: asdf
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  gpt-heist-db-data:
  pgadmin-data: